### ISSUE TITLE
Sumiço dos documentos oficiais

### ISSUE THREAD

**Issue by joaocaram** [DisciplinasProgramacao/lpm_projetos_3_4_5-grupo6#35]
@yzPeedro @ericdiniz @pauloroncarati @FelipeVieir4 @GustavoRiegert 
Pessoal, vocês fizeram algum merge aí que sumiu com todos os arquivos MD da master. Por favor deem uma olhada e corrijam isso. Os MD são importantes para o acompanhamento e correção.

**Comment by FelipeVieir4** [comment]
Prezado Professor @joaocaram . 
Já identificamos os problema e vamos corrigir para a próxima entrega. 

Obrigado pelo aviso. 

Atenciosamente,

**Comment by pauloroncarati** [comment]
@FelipeVieir4 atribuí a vc, se não concordar pode colocar pra mim sem stress

**Comment by FelipeVieir4** [comment]
@pauloroncarati , está feito e na fila de pull request.
