### ISSUE TITLE
Plataforma Streaming

### ISSUE THREAD

**Issue by pauloroncarati** [DisciplinasProgramacao/lpm_projetos_3_4_5-grupo6#5]

**Comment by joaocaram** [comment]
@pauloroncarati , boa tarde. Não precisa (e nem deve) usar o contains. Se a chave já existir, o put vai retornar o objeto antigo. Então é só chegar o retorno do put. Se for diferente de nulo, é porque já tinha alguém com aquela chave. Você pode inserir ele de volta e então retornar o erro para o sistema (iremos melhorar isso no futuro)
